---
# tasks file for install_mariadb
- name: install curl-config
  apt: pkg=libcurl4-openssl-dev state=latest


- name: install python-pycurl
  pip: name=pycurl state=latest


- name: install mariadb addons
  apt: pkg=software-properties-common state=latest


- name: add mariadb key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name: add mariadb repository
  apt_repository: repo='deb https://mariadb.mirror.liquidtelecom.com/repo/10.7/ubuntu precise main'


