---
# tasks file for MySQL
- name: Install the MySQL
  yum:
    name: https://dev.mysql.com/get/mysql80-com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: present
    update_cache: yes
  notify:
    - Restart MYSQL
