---
# tasks file for PHP
- name: Install the remi rpm
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
    update_cache: yes

- name: Install a PHP with packages
  yum:
    name: "{{ packages }}"
    enablerepo: "remi-php73"
  vars:
    packages:
      - php
      - php-cli
      - php-fpm
      - php-mysqlnd
      - php-zip
      - php-devel
      - php-gd
      - php-mcrypt
      - php-mbstring
      - php-curl
      - php-xml
      - php-pear
      - php-bcmath
      - php-json
