Vagrant.configure("2") do |config|

   config.vm.box = "ubuntu1804"
   config.vm.synced_folder "/tmp", "/vagrant", disabled: 'true'
   config.ssh.username = 'vagrant'
   config.ssh.password = 'vagrant'
  #  config.vm.network "forwarded_port", guest: 22, host: 22022
  #  config.vm.network "forwarded_port", guest: 80, host: 22080
  #  config.vm.network "forwarded_port", guest: 443, host: 22443
  #  config.vm.network "forwarded_port", guest: 3306, host: 22306
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
