
Vagrant.configure("2") do |config|
  config.vm.box = "virtualbox-ubuntu-18-04.box"
  config.vm.synced_folder "/vagrant", disabled: 'true'
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
end
