---
# tasks file for haproxy
- name: Install haproxy
  apt:
    name: haproxy
    update_cache: yes
  

- name: Configure config file haproxy
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg


- name: start haproxy
  service:
    name: haproxy
    state: started
